#attool = casac.homefinder.find_home_by_name('atmosphereHome')
myat = casac.atmosphere()
print((myat.initAtmProfile(dP=qa.quantity(5.0,'mbar'),dPm=1.1)))
l = myat.getProfile()
print((l[0]))
#print "Output record keys: ", l.keys()
#exit()
