from taskinit import casalog
from visstat import visstat

def visstat2(vis=None,
             axis=None,
             datacolumn=None,
             useflags=None,
             spw=None,
             field=None,
             selectdata=None,
             antenna=None,
             uvrange=None,
             timerange=None,
             correlation=None,
             scan=None,
             array=None,
             observation=None,
             timeaverage=None,
             timebin=None,
             timespan=None,
             maxuvwdistance=None,
             disableparallel=None,
             ddistart=None,
             taql=None,
             monolithic_processing=None,
             intent=None,
             reportingaxes=None):

    casalog.origin('visstat2')
    casalog.post("Task visstat2 has been deprecated and will be removed in release 5.4.", "WARN")
    casalog.post('"visstat2" has been renamed "visstat"; use of visstat2 is deprecated; please replace calls to visstat2 with calls to visstat', priority='INFO')

    return visstat(vis,
                   axis,
                   datacolumn,
                   useflags,
                   spw,
                   field,
                   selectdata,
                   antenna,
                   uvrange,
                   timerange,
                   correlation,
                   scan,
                   array,
                   observation,
                   timeaverage,
                   timebin,
                   timespan,
                   maxuvwdistance,
                   disableparallel,
                   ddistart,
                   taql,
                   monolithic_processing,
                   intent,
                   reportingaxes)
